### ISSUE TITLE
ArgumentOutOfRangeException when empty data source

### ISSUE THREAD

**Issue by b0bi79** [ClosedXML/ClosedXML.Report#83]
If the template has conditional formatting, then generating a report with an empty data source ends with an error ArgumentOutOfRangeException.

**Comment by BenKmann** [comment]
As an Extension to this. This Bug should be solved with any Tag / Formatting.

When the Tag <<group>> is used and you generate a report with an empty DataSource you get a InvalidOperationException "Sequence contains no Elements".

Stacktrace:
> bei System.Linq.Enumerable.Max(IEnumerable`1 source)
>    bei ClosedXML.Report.Excel.Subtotal.GroupBy(Int32 groupBy, SubtotalSummaryFunc[] summaries, Boolean pageBreaks, Func`2 getGroupLabel)
>    bei ClosedXML.Report.Options.GroupTag.Process(IXLRange root, GroupTag[] groups, Boolean summaryAbove, SubtotalSummaryFunc[] funcs, Boolean disableGrandTotal)
>    bei ClosedXML.Report.Options.GroupTag.Execute(ProcessingContext context)
>    bei ClosedXML.Report.Options.TagsList.Execute(ProcessingContext context)
>    bei ClosedXML.Report.RangeTemplate.RangeTagsApply(IXLRange range, Object[] items)
>    bei ClosedXML.Report.RangeInterpreter.EvaluateValues(IXLRange range, Parameter[] pars)
>    bei ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
>    bei ClosedXML.Report.XLTemplate.Generate()

**Comment by b0bi79** [comment]
Thanks.
I have already fixed it, but I'm waiting for the release of ClosedXML. If you need urgently, I can create a commit with a fix.

**Comment by BenKmann** [comment]
b0bi79 Thanks! Great Commit I like it. Looks promising, will try it later.
Now i only have the issue #88 left, that makes it hard to Design my File.

**Comment by BenKmann** [comment]
Ok Testet you're Code. Works good, but one Exception still comes.
I still get an Exception. Nullref because of the RowsFitTag.

>   bei ClosedXML.Report.Options.RowsFitTag.Execute(ProcessingContext context)
>    bei ClosedXML.Report.Options.TagsList.Execute(ProcessingContext context)
>    bei ClosedXML.Report.RangeTemplate.RangeTagsApply(IXLRange range, Object[] items)
>    bei ClosedXML.Report.RangeInterpreter.EvaluateValues(IXLRange range, Parameter[] pars)
>    bei ClosedXML.Report.RangeInterpreter.Evaluate(IXLRange range)
>    bei ClosedXML.Report.XLTemplate.Generate()

**Comment by b0bi79** [comment]
Under what conditions do you get this error?

**Comment by BenKmann** [comment]
Condition is, Empty Datasource + i use the following Tags in Column A
<<summaryabove>><<DisableGrandTotal>><<RowsFit>>

RowsFit than is pretty unhappy about the 0 rows.
If i Remove <<RowsFit>> the Exception disappears. The Stacktrace also says <<RowsFit>>

**Comment by b0bi79** [comment]
Thanks, I'll check it out.

**Comment by b0bi79** [comment]
@BenKmann, hi. I'm trying to reproduce the error with RowsFit, but I can't. Please attach your template.
